### ISSUE TITLE
Label here should be "View system in Inventory" not "View in Inventory"

### ISSUE THREAD

**Issue by katierik** [RedHatInsights/frontend-components#1095]
https://github.com/RedHatInsights/frontend-components/blob/4c5456bd2b27497fbc8849bf5aad99be1d6fb755/packages/inventory/src/components/detail/TopBar.js#L43

Reasoning: "View in Inventory" is not precise, and could refer to, for example, "View this list of CVEs in the Inventory"; vs "View system in Inventory" tells the user exactly what to expect.

**Comment by rvsia** [comment]
cc @karelhala
