### ISSUE TITLE
[BUG] Updating utilities to version 3.2.3 show error message

### ISSUE THREAD

**Issue by boaz0** [RedHatInsights/frontend-components#1202]
**Describe the bug**
Updating `@redhat-cloud-services/frontend-components-utilities` to `2.3.2` shows error message

**To Reproduce**
1. Update in package.json `@redhat-cloud-services/frontend-components-utilities` to 2.3.2
2. Run `npm i`
3. `npm start`

**Expected behavior**
No error messages

**Screenshots**
![Screenshot from 2021-06-29 08-23-58](https://user-images.githubusercontent.com/2453279/123857379-e0e6ad80-d92a-11eb-809f-354662033079.png)

**Comment by kgaikwad** [comment]
I am facing this issue while updating `@redhat-cloud-services/frontend-components-utilities` from `3.2.1` to `3.2.21`.

**Comment by Hyperkid123** [comment]
@boaz0 @kgaikwad did you also update the `@redhat-cloud-services/frontend-components-config`? The problem is that `node-sass` is deprecated so you should use `sass` instead. The new version of the shared config have migrated over.

**Comment by Hyperkid123** [comment]
Also you should be on v3 of `@redhat-cloud-services/frontend-components-utilities`. v2 is very old by now.

**Comment by boaz0** [comment]
:+1:  @matoval -> this is for you.

**Comment by Hyperkid123** [comment]
Just to give a context. node-sass is deprecated by node-sass not us. It does not work properly on the latest versions of node. Hence the change.

**Comment by matoval** [comment]
> Thanks  @Hyperkid123
> @matoval can you take over this and update the packages as mentioned here. Thanks.

Thanks @boaz0 I updated `@redhat-cloud-services/frontend-components-utilities` to 3.2.3, installed sass and it's working great.

**Comment by kgaikwad** [comment]
Updated `@redhat-cloud-services/frontend-components-utilities` to 3.2.3. Removed deprecated node-sass and installed sass instead. Thank you @Hyperkid123 once again.

**Comment by Hyperkid123** [comment]
@boaz0 do you still have this issue after updating the dependencies? Or can we close this?

**Comment by boaz0** [comment]
@Hyperkid123 it was resolved. I am closing this now.
Thanks a lot!
