### ISSUE TITLE
[BUG] fallback property is ignored by AsyncComponent

### ISSUE THREAD

**Issue by gkarat** [RedHatInsights/frontend-components#1221]
**Describe the bug**
When the `fallback` property is provided to the `AsyncComponent` component (`@redhat-cloud-services/frontend-components/AsyncComponent`), it will always show only the "loading" message instead of the sent fallback component.

**To Reproduce**
1. Import AsyncComponent from '@redhat-cloud-services/frontend-components/AsyncComponent.'
2. Try to provide it with valid appName and module (e.g., I used appName="advisor" and module="./AdvisorReportDetails").
3. Also provide custom fallback component sent via `fallback` property (e.g. fallback={"test"}).
4. Render the component that imported AsyncComponent.
5. When a component is in the loading state, it will render 'loading' text instead of the provided custom fallback ("test" in my example).

**Expected behavior**
Custom fallback is rendered instead of "loading" text.

**Desktop (please complete the following information):**
- "@redhat-cloud-services/frontend-components": "3.3.5"

**Additional context**
While debugging, I have found the possible line that can be the source of the problem: https://github.com/scalprum/scaffloding/blob/main/packages/react-core/src/scalprum-component.tsx#L21. But TBH, properties are normally sent, and the "loading" text is here as a default parameter. So when I have fallback defined and sent via props, this default value should be ignored. Didn't have more time to debug it further, so mentioning the issue here.

**Comment by rvsia** [comment]
Fixed by Update async component
