### ISSUE TITLE
[BUG] The emptyStateIcon causes unit tests to fail

### ISSUE THREAD

**Issue by Fewwy** [RedHatInsights/frontend-components#1236]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. Writing a basic shallow snapshot test for the class that has RuleTable inside of it
```
const wrapper = shallow(<My Component  {...some props}/>) 
 it('component renders correctly', () => {
    expect(wrapper).toMatchSnapshot();
  });
```
3. The test is failing because 
```
Failed prop type: Invalid prop `emptyStateIcon` supplied to `RuleTable`, expected a ReactNode.
        in RuleTable
```
4. I tried to solve it but the only way that helped is actually removing 
`emptyStateIcon: SearchIcon`
from line 284

**Expected behavior**
 Tests are working :) 

**Desktop (please complete the following information):**
 - OS: Fedora 33
 - Browser Chrome Version 92.0.4515.131 (Official Build) (64-bit)

**Additional context**

**Comment by rvsia** [comment]
Thank you for noticing this! There is a wrong proptype, fixed here: https://github.com/RedHatInsights/frontend-components/pull/1237/files
