### ISSUE TITLE
Battery.js

### ISSUE THREAD

**Issue by fhlavac** [RedHatInsights/frontend-components#1340]
file: https://github.com/RedHatInsights/frontend-components/tree/master/packages/components/src/Battery/Battery.js

**Comment by uravgkarthik** [comment]
Hey @fhlavac 
May I work on this issue as I am new to TS and am trying to get my hands on it?

**Comment by Hyperkid123** [comment]
@uravgkarthik these issues were specifically assigned to @fhlavac. I can find you others if you want.
