### ISSUE TITLE
Typescript definitions for @redhat-cloud-services/frontend-components-notifications

### ISSUE THREAD

**Issue by riccardo-forina** [RedHatInsights/frontend-components#1551]
While setting up a stricter TS configuration for app-services-ui I noticed that @redhat-cloud-services/frontend-components-notifications doesn't ship with the TS definitions. 

Is this by design, can I find them somewhere else?

**Comment by Hyperkid123** [comment]
We are gradually migrating to TS and generating TS definitions for packages in this repository. The notifications package was migrated.

I have just checked and we are missings the `typings` attribute in the notifications module: https://github.com/RedHatInsights/frontend-components/blob/master/packages/notifications/package.json#L1
