### ISSUE TITLE
### tagFilterHook.tsx

### ISSUE THREAD

**Issue by nicolethoen** [RedHatInsights/frontend-components#1791]
file: https://github.com/RedHatInsights/frontend-components/tree/master/packages/components/src/FilterHooks/tagFilterHook.tsx
 #### Ensure PF4@5 compatibility

**Comment by wise-king-sullyman** [comment]
Can take this

**Comment by nicolethoen** [comment]
unclear how to test this

**Comment by Hyperkid123** [comment]
@RedHatInsights/platform-experience this one is complex, need some eyes on this one.
