### ISSUE TITLE
### InvalidObject.tsx

### ISSUE THREAD

**Issue by nicolethoen** [RedHatInsights/frontend-components#1792]
file: https://github.com/RedHatInsights/frontend-components/tree/master/packages/components/src/InvalidObject/InvalidObject.tsx
 #### Ensure PF4@5 compatibility

**Comment by thatblindgeye** [comment]
I'll take this

**Comment by thatblindgeye** [comment]
I'm not noticing any visual discrepancies between `pf4@5` and `master`.
