### ISSUE TITLE
### SkeletonTable.tsx

### ISSUE THREAD

**Issue by nicolethoen** [RedHatInsights/frontend-components#1793]
file: https://github.com/RedHatInsights/frontend-components/tree/master/packages/components/src/SkeletonTable/SkeletonTable.tsx
 #### Ensure PF4@5 compatibility

**Comment by wise-king-sullyman** [comment]
👋

**Comment by wise-king-sullyman** [comment]
Everything that I've tried looks good, but the API has changed significantly between the old and new versions here, is that intended?

For instance the v4 version had an `isSelectable` prop, which does not have similar functionality in the new version.

**Comment by Hyperkid123** [comment]
> Everything that I've tried looks good, but the API has changed significantly between the old and new versions here, is that intended?
> 
> For instance the v4 version had an `isSelectable` prop, which does not have similar functionality in the new version.

Yeah, the API changes are intended. The component now uses the "regular" table.
