### ISSUE TITLE
### PageHeader.tsx

### ISSUE THREAD

**Issue by nicolethoen** [RedHatInsights/frontend-components#1797]
file: https://github.com/RedHatInsights/frontend-components/tree/master/packages/components/src/PageHeader/PageHeader.tsx
 #### Ensure PF4@5 compatibility

**Comment by thatblindgeye** [comment]
I'll take this

**Comment by thatblindgeye** [comment]
No discrepancies noticed, though this isn't importing anything from PatternFly and instead applying hardcoded PF classes.

It doesn't look like the `pf-v5-c-page-header` being hardcoded is being used anywhere in the codebase currently (not sure if it'd be being used outside, though)

**Comment by Hyperkid123** [comment]
> pf-v5-c-page-header

I don't think we use the class anywhere. I'll mark this for a tech debt clean up.
