### ISSUE TITLE
### TabLayout.tsx

### ISSUE THREAD

**Issue by nicolethoen** [RedHatInsights/frontend-components#1799]
file: https://github.com/RedHatInsights/frontend-components/tree/master/packages/components/src/TabLayout/TabLayout.tsx
 #### Ensure PF4@5 compatibility

**Comment by thatblindgeye** [comment]
This component isn't currently using any PatternFly components/classes on either `master` or `pf4@5` (there is only a comment about this being deprecated and to eventually use PF Tabs instead). So this should be okay to mark as done
