### ISSUE TITLE
### FilterChips.tsx

### ISSUE THREAD

**Issue by nicolethoen** [RedHatInsights/frontend-components#1801]
file: https://github.com/RedHatInsights/frontend-components/tree/master/packages/components/src/FilterChips/FilterChips.tsx
 #### Ensure PF4@5 compatibility

**Comment by kmcfaul** [comment]
👍

**Comment by nicolethoen** [comment]
I think we might be able to provide a quick CSS override to add some marginLeft as a quick fix in this case.
