### ISSUE TITLE
### RuleDescription.tsx

### ISSUE THREAD

**Issue by nicolethoen** [RedHatInsights/frontend-components#1803]
file: https://github.com/RedHatInsights/frontend-components/tree/master/packages/advisor-components/src/RuleDescription/RuleDescription.tsx
 #### Ensure PF4@5 compatibility

**Comment by kmcfaul** [comment]
Having trouble importing this component into the demo app properly. Code-wise the only PF class this component uses (`--pf-global--spacer--md`) probably should not have changed in value in the v5 update, but a core dev can verify.

**Comment by Hyperkid123** [comment]
Seems to be working just fine. Its just a wrapper around a MD component.
