### ISSUE TITLE
### InsightsLink.tsx

### ISSUE THREAD

**Issue by nicolethoen** [RedHatInsights/frontend-components#1804]
file: https://github.com/RedHatInsights/frontend-components/tree/master/packages/components/src/InsightsLink/InsightsLink.tsx
 #### Ensure PF4@5 compatibility

**Comment by jenny-s51** [comment]
I'll take this one

**Comment by jenny-s51** [comment]
Having trouble rendering this component directly in the demo code. Tried using it from within a PF button as well.

**Comment by Hyperkid123** [comment]
THis one requires the chrome context. I would say we give it a pass as its just a wrapper around a link. No visuals to look at.
