### ISSUE TITLE
### ErrorBoundary.tsx

### ISSUE THREAD

**Issue by nicolethoen** [RedHatInsights/frontend-components#1805]
file: https://github.com/RedHatInsights/frontend-components/tree/master/packages/components/src/ErrorBoundary/ErrorBoundary.tsx
 #### Ensure PF4@5 compatibility

**Comment by thatblindgeye** [comment]
🛄

**Comment by thatblindgeye** [comment]
Only difference is the icon above the "Something went wrong" text no longer having the same color.

`pf4@5`:
![image](https://github.com/RedHatInsights/frontend-components/assets/70952936/4ce9233f-1257-4b7b-ba13-373393366faa)

`master`
![image](https://github.com/RedHatInsights/frontend-components/assets/70952936/5916317c-7e9f-43c1-a02c-fb642981fa9a)

This should be resolved by passing the `color` prop into `EmptyStateIcon` within your `ErrorState` component (line ~26). We have an [empty state with custom icon color example](https://www.patternfly.org/components/empty-state#custom-icon-color) that showcases this
