### ISSUE TITLE
### BulkSelect.tsx

### ISSUE THREAD

**Issue by nicolethoen** [RedHatInsights/frontend-components#1812]
file: https://github.com/RedHatInsights/frontend-components/tree/master/packages/components/src/BulkSelect/BulkSelect.tsx
 #### Ensure PF4@5 compatibility

**Comment by wise-king-sullyman** [comment]
🇮🇲

**Comment by wise-king-sullyman** [comment]
Slight visual difference: arrow is moved out by a small amount and checkbox is moved vertically by a very small amount.
<img width="1084" alt="image" src="https://github.com/RedHatInsights/frontend-components/assets/7115053/92ccc7aa-da5b-4036-98ec-c56c1c0992d4">

Slight visual difference in shading of the down arrow when disabled
<img width="1071" alt="image" src="https://github.com/RedHatInsights/frontend-components/assets/7115053/80000286-5151-4614-a6e3-352a95d427d9">


Slight behavior difference, the v4 version requires clicking on the dropdown arrow to open, but the v5 version allows clicking anywhere.

Other than those items it looks good.

**Comment by Hyperkid123** [comment]
I think we can call this an acceptable difference after the upgrade.
