### ISSUE TITLE
### CullingInformation.tsx

### ISSUE THREAD

**Issue by nicolethoen** [RedHatInsights/frontend-components#1813]
file: https://github.com/RedHatInsights/frontend-components/tree/master/packages/components/src/CullingInfo/CullingInformation.tsx
 #### Ensure PF4@5 compatibility

**Comment by thatblindgeye** [comment]
I'll take this

**Comment by thatblindgeye** [comment]
Not noticing any discrepancies.

Wanted to note that in the demo build in the `pf4@5` branch there is some brief "flickering" when the tooltip renders. We did merge a PR in our React repo after the release of v5 (https://github.com/patternfly/patternfly-react/pull/9339) that should resolve that.
