### ISSUE TITLE
### OpenSourceBadge.tsx

### ISSUE THREAD

**Issue by nicolethoen** [RedHatInsights/frontend-components#1820]
file: https://github.com/RedHatInsights/frontend-components/tree/master/packages/components/src/OpenSourceBadge/OpenSourceBadge.tsx
 #### Ensure PF4@5 compatibility

**Comment by kmcfaul** [comment]
🦡

**Comment by kmcfaul** [comment]
Master popover had some trouble not adapting position, but the v5 branch looks okay. After manually readjusting the master popover position it looks the same as v5.

master:
<img width="435" alt="image" src="https://github.com/RedHatInsights/frontend-components/assets/45077788/c14d1305-65eb-40fb-9e0a-7055b80dd636">
(manually moved popover)
<img width="435" alt="image" src="https://github.com/RedHatInsights/frontend-components/assets/45077788/5fa5a358-67f1-4b7a-82f8-2e0d9ee7f7e9">

pf4@5:
<img width="435" alt="image" src="https://github.com/RedHatInsights/frontend-components/assets/45077788/4654f080-6e8a-4f67-829e-c53a7e186246">
