### ISSUE TITLE
### RBACProvider.tsx

### ISSUE THREAD

**Issue by nicolethoen** [RedHatInsights/frontend-components#1821]
file: https://github.com/RedHatInsights/frontend-components/tree/master/packages/components/src/RBACProvider/RBACProvider.tsx
 #### Ensure PF4@5 compatibility

**Comment by wise-king-sullyman** [comment]
🐞

**Comment by wise-king-sullyman** [comment]
Bit of a visual difference in the Spinner:
<img width="1138" alt="image" src="https://github.com/RedHatInsights/frontend-components/assets/7115053/e8b6ac57-19c3-4e11-b8ca-856c9d7a72cb">

**Comment by Hyperkid123** [comment]
I noticed that the spinner is "thinner" in v5. Is that expected?

**Comment by nicolethoen** [comment]
I am investigating

**Comment by nicolethoen** [comment]
Can confirm - it is an expected change!
It's rendered using an SVG now rather than pure CSS.
