### ISSUE TITLE
### RuleRating.tsx

### ISSUE THREAD

**Issue by nicolethoen** [RedHatInsights/frontend-components#1824]
file: https://github.com/RedHatInsights/frontend-components/tree/master/packages/advisor-components/src/RuleRating/RuleRating.tsx
 #### Ensure PF4@5 compatibility

**Comment by thatblindgeye** [comment]
⭐

**Comment by thatblindgeye** [comment]
Only difference is the size of the icons

`pf4@5`:
![image](https://github.com/RedHatInsights/frontend-components/assets/70952936/c7b2bb50-05ec-48b8-940e-3a74a14d7c8c)


`master`:
![image](https://github.com/RedHatInsights/frontend-components/assets/70952936/1e165fd5-4e74-48dd-9bd0-22c3a9231eac)
