### ISSUE TITLE
### OuiaSelectors.test.tsx

### ISSUE THREAD

**Issue by nicolethoen** [RedHatInsights/frontend-components#1825]
file: https://github.com/RedHatInsights/frontend-components/tree/master/packages/testing/src/OuiaSelectors/OuiaSelectors.test.tsx
 #### Ensure PF4@5 compatibility

**Comment by jenny-s51** [comment]
I can take this one

**Comment by jenny-s51** [comment]
Same as #1874 , no PF classes or components used here, however v5 components support more ouia properties now
