### ISSUE TITLE
### Actions.tsx

### ISSUE THREAD

**Issue by nicolethoen** [RedHatInsights/frontend-components#1830]
file: https://github.com/RedHatInsights/frontend-components/tree/master/packages/components/src/PrimaryToolbar/Actions.tsx
 #### Ensure PF4@5 compatibility

**Comment by kmcfaul** [comment]
🦖

**Comment by Hyperkid123** [comment]
I'd say these changes are nothing we should block the release one. Can be addressed separately later.
