### ISSUE TITLE
### WithOuia.tsx

### ISSUE THREAD

**Issue by nicolethoen** [RedHatInsights/frontend-components#1838]
file: https://github.com/RedHatInsights/frontend-components/tree/master/packages/components/src/Ouia/WithOuia.tsx
 #### Ensure PF4@5 compatibility

**Comment by jenny-s51** [comment]
I can take this one

**Comment by jenny-s51** [comment]
Same as comment in #1874 , no PF classes or imports used here however v5 components now support more ouia properties
