### ISSUE TITLE
### GroupFilter.tsx

### ISSUE THREAD

**Issue by nicolethoen** [RedHatInsights/frontend-components#1841]
file: https://github.com/RedHatInsights/frontend-components/tree/master/packages/components/src/ConditionalFilter/GroupFilter.tsx
 #### Ensure PF4@5 compatibility

**Comment by wise-king-sullyman** [comment]
🦘

**Comment by wise-king-sullyman** [comment]
The Menu now renders with the minimum width needed to show its contents. Seems like a pretty clear bugfix/improvement to me but figured it was worth noting.
<img width="1162" alt="image" src="https://github.com/RedHatInsights/frontend-components/assets/7115053/d6e0c707-7ed2-4960-b994-424c5ed1cf59">

When it is filterable an X now appears to clear the input
<img width="1185" alt="image" src="https://github.com/RedHatInsights/frontend-components/assets/7115053/0974f52c-d867-4b64-9deb-1720f00c23be">

Slight change in text color when disabled
<img width="1167" alt="image" src="https://github.com/RedHatInsights/frontend-components/assets/7115053/5f30a326-d3c9-4d26-acf6-ea61230a0749">

Other than those items everything here looks great from what I can tell, admittedly though this has been one of the more difficult ones to really figure out and test thoroughly.
