### ISSUE TITLE
### ErrorStack.tsx

### ISSUE THREAD

**Issue by nicolethoen** [RedHatInsights/frontend-components#1842]
file: https://github.com/RedHatInsights/frontend-components/tree/master/packages/components/src/ErrorBoundary/ErrorStack.tsx
 #### Ensure PF4@5 compatibility

**Comment by kmcfaul** [comment]
🏟️

**Comment by kmcfaul** [comment]
Actually this isn't exported; and is tested as part of `ErrorBoundary`.
