### ISSUE TITLE
### TextFilter.tsx

### ISSUE THREAD

**Issue by nicolethoen** [RedHatInsights/frontend-components#1843]
file: https://github.com/RedHatInsights/frontend-components/tree/master/packages/components/src/ConditionalFilter/TextFilter.tsx
 #### Ensure PF4@5 compatibility

**Comment by kmcfaul** [comment]
🔤

**Comment by kmcfaul** [comment]
Size of icon needs to be updated to `md` to match master, color change is expected from v5 update but could be updated with the custom css to match master as well. I'm not sure why master's TextFilter is pushing the icon out of the input, as this didn't happen in testing `ConditionalFilter` which uses `TextFilter` or in the pf4@5 branch.

master:
<img width="1422" alt="image" src="https://github.com/RedHatInsights/frontend-components/assets/45077788/2113eba4-da26-4ec7-a250-b2fd264b4441">

pf4@5:
<img width="1422" alt="image" src="https://github.com/RedHatInsights/frontend-components/assets/45077788/eefa00a9-c772-47d6-9b2f-275228002650">
