### ISSUE TITLE
### DateFormat.tsx

### ISSUE THREAD

**Issue by nicolethoen** [RedHatInsights/frontend-components#1844]
file: https://github.com/RedHatInsights/frontend-components/tree/master/packages/components/src/DateFormat/DateFormat.tsx
 #### Ensure PF4@5 compatibility

**Comment by nicolethoen** [comment]
🧽

**Comment by nicolethoen** [comment]
This seems to be working as expected. It's worth noting that PF does have a [timestamp component ](https://www.patternfly.org/components/timestamp#default-tooltip) that does much of the same as this DateFormat component, plus more. The most notable difference is that the tooltip can be triggered by keyboard as well as read by a screen reader in the PF component, and is therefore more accessible. @Hyperkid123 @florkbr

**Comment by Hyperkid123** [comment]
Thanks for the update. We will update the component to use the timestamp component. Should be a separate issue. Closing for now.
