### ISSUE TITLE
### ReportDetails.tsx

### ISSUE THREAD

**Issue by nicolethoen** [RedHatInsights/frontend-components#1845]
file: https://github.com/RedHatInsights/frontend-components/tree/master/packages/advisor-components/src/ReportDetails/ReportDetails.tsx
 #### Ensure PF4@5 compatibility

**Comment by kmcfaul** [comment]
🔴

**Comment by kmcfaul** [comment]
Having a hard time demoing ReportDetails, it won't render after getting error from the usage of `isProd` within the component.

**Comment by Hyperkid123** [comment]
I've tested this in product and it looks OK.
