### ISSUE TITLE
### Truncate.tsx

### ISSUE THREAD

**Issue by nicolethoen** [RedHatInsights/frontend-components#1850]
file: https://github.com/RedHatInsights/frontend-components/tree/master/packages/components/src/Truncate/Truncate.tsx
 #### Ensure PF4@5 compatibility

**Comment by kmcfaul** [comment]
🐘

**Comment by kmcfaul** [comment]
No changes.

master:
<img width="215" alt="image" src="https://github.com/RedHatInsights/frontend-components/assets/45077788/77c787f9-6160-40c5-ab24-27cca0f5a80b">
expanded:
<img width="1421" alt="image" src="https://github.com/RedHatInsights/frontend-components/assets/45077788/923921bb-25fa-4501-8d84-7b377b411a98">


pf4@5:
<img width="215" alt="image" src="https://github.com/RedHatInsights/frontend-components/assets/45077788/57b60a8c-4ff4-47ab-bb5b-5197d1a80030">
expanded:
<img width="1421" alt="image" src="https://github.com/RedHatInsights/frontend-components/assets/45077788/30bc2c97-7996-4b22-bd42-b8296cc29614">
