### ISSUE TITLE
### FilterDropdown.tsx

### ISSUE THREAD

**Issue by nicolethoen** [RedHatInsights/frontend-components#1854]
file: https://github.com/RedHatInsights/frontend-components/tree/master/packages/components/src/Filters/FilterDropdown.tsx
 #### Ensure PF4@5 compatibility

**Comment by kmcfaul** [comment]
🐉

**Comment by kmcfaul** [comment]
Unsure why master is having an issue with the group label but may be my demo setup. pf4@5 looks correct, though in the code the extra wrapping `MenuList` shouldn't be required and can be removed.

master:
<img width="230" alt="image" src="https://github.com/RedHatInsights/frontend-components/assets/45077788/56305f24-736d-4025-a7ed-fa5f119ad834">

pf4@5:
<img width="230" alt="image" src="https://github.com/RedHatInsights/frontend-components/assets/45077788/b8146f22-f8da-4a90-9c43-c3afc9cc0666">

**Comment by kmcfaul** [comment]
Without the extra menu list
<img width="230" alt="image" src="https://github.com/RedHatInsights/frontend-components/assets/45077788/820653f8-f460-4f6b-9ccf-97045da533e4">

**Comment by nicolethoen** [comment]
Probably should make this change - or at least run a11y tests on it.
