### ISSUE TITLE
### TagModal.tsx

### ISSUE THREAD

**Issue by nicolethoen** [RedHatInsights/frontend-components#1862]
file: https://github.com/RedHatInsights/frontend-components/tree/master/packages/components/src/TagModal/TagModal.tsx
 #### Ensure PF4@5 compatibility

**Comment by jenny-s51** [comment]
I can take this one

**Comment by jenny-s51** [comment]
Several TS errors related to unused props that are required in `TagModal`: missing `title`, `toggleModal`, `columns`, and `pagination`.

Pagination bug fixed if `pagination` prop is declared, other than that just some minor spacing differences. 

<img width="857" alt="Screenshot 2023-08-11 at 1 36 22 PM" src="https://github.com/RedHatInsights/frontend-components/assets/32821331/3a532ad9-8fd7-4dc1-bfaa-e50c408e962e">
<img width="855" alt="Screenshot 2023-08-11 at 1 36 16 PM" src="https://github.com/RedHatInsights/frontend-components/assets/32821331/d5799d75-53f2-4730-a804-c8115f3d1b2b">

**Comment by nicolethoen** [comment]
so the unit tests are lacking some required props - would be addressed during a typescript clean up effort

**Comment by jenny-s51** [comment]
> so the unit tests are lacking some required props - would be addressed during a typescript clean up effort

yes, I pulled this code from TagModal.test.js

**Comment by Hyperkid123** [comment]
I've verified this component in chrome UI as well and works fine.
