### ISSUE TITLE
### TagWithDialog.tsx

### ISSUE THREAD

**Issue by nicolethoen** [RedHatInsights/frontend-components#1864]
file: https://github.com/RedHatInsights/frontend-components/tree/master/packages/components/src/Inventory/TagWithDialog.tsx
 #### Ensure PF4@5 compatibility

**Comment by kmcfaul** [comment]
🏷️

**Comment by kmcfaul** [comment]
Can't get the demo to run with scalprum initialization. Bullseye hasn't changed going to v5, and Spinner should now be an svg by default (but shouldn't look different).

**Comment by Hyperkid123** [comment]
Tested in chrome, works as expected.
