### ISSUE TITLE
### ConnectedBreadcrumbs.tsx

### ISSUE THREAD

**Issue by nicolethoen** [RedHatInsights/frontend-components#1865]
file: https://github.com/RedHatInsights/frontend-components/tree/master/packages/components/src/Breadcrumbs/ConnectedBreadcrumbs.tsx
 #### Ensure PF4@5 compatibility

**Comment by jenny-s51** [comment]
🍞

**Comment by jenny-s51** [comment]
N/A - according to comments in file, `ConnectedBreadcrumbs` is deprecated and should be removed in favor of using PatternFly's breadcrumb component directly
