### ISSUE TITLE
### SimpleTableFilter.test.tsx

### ISSUE THREAD

**Issue by nicolethoen** [RedHatInsights/frontend-components#1866]
file: https://github.com/RedHatInsights/frontend-components/tree/master/packages/components/src/SimpleTableFilter/SimpleTableFilter.test.tsx
 #### Ensure PF4@5 compatibility

**Comment by kmcfaul** [comment]
🎐

**Comment by kmcfaul** [comment]
Dropdown and button are the same minus some small spacing differences that are expected with v5 updates. Both branches are missing styles (the custom class and the pf input group class that's manually added is missing on both and the form control styling on the input on master) but I'm unsure why it's only a few classes while others are properly included.

master:
<img width="1421" alt="image" src="https://github.com/RedHatInsights/frontend-components/assets/45077788/b8f7c8f7-530d-4102-9102-d97ca6451173">

pf4@5:
<img width="1421" alt="image" src="https://github.com/RedHatInsights/frontend-components/assets/45077788/e6112482-0679-4117-b5c0-8ef6d5dd9c7e">
If the missing input group class is present it would look like:
<img width="1421" alt="image" src="https://github.com/RedHatInsights/frontend-components/assets/45077788/e0a86c0b-e263-4a63-b242-572f18514812">
