### ISSUE TITLE
### index.tsx

### ISSUE THREAD

**Issue by nicolethoen** [RedHatInsights/frontend-components#1867]
file: https://github.com/RedHatInsights/frontend-components/tree/master/packages/components/src/AsyncComponent/index.tsx
 #### Ensure PF4@5 compatibility

**Comment by kmcfaul** [comment]
🔢

**Comment by kmcfaul** [comment]
Having trouble testing in demo because of required scalprum initialization. Bullseye hasn't changed going to v5, and Spinner should now be an svg by default (but shouldn't look different).

**Comment by Hyperkid123** [comment]
No need to test this one. Has been verified in product.
