### ISSUE TITLE
### ViewAffectedLink.tsx

### ISSUE THREAD

**Issue by nicolethoen** [RedHatInsights/frontend-components#1869]
file: https://github.com/RedHatInsights/frontend-components/tree/master/packages/advisor-components/src/ViewAffectedLink/ViewAffectedLink.tsx
 #### Ensure PF4@5 compatibility

**Comment by kmcfaul** [comment]
No direct usage of PF components/classes. Rendered content `Message` should be evaluated in `RuleDetails`.
