### ISSUE TITLE
### InsightsLabel.tsx

### ISSUE THREAD

**Issue by nicolethoen** [RedHatInsights/frontend-components#1870]
file: https://github.com/RedHatInsights/frontend-components/tree/master/packages/components/src/InsightsLabel/InsightsLabel.tsx
 #### Ensure PF4@5 compatibility

**Comment by kmcfaul** [comment]
📦

**Comment by kmcfaul** [comment]
Unchanged.

master: 
<img width="350" alt="image" src="https://github.com/RedHatInsights/frontend-components/assets/45077788/d890f667-a9e5-4663-8961-37893a09e858">

pf4@5:
<img width="350" alt="image" src="https://github.com/RedHatInsights/frontend-components/assets/45077788/3c60c92b-9ff4-4365-b59a-c77d9e990eb6">
