### ISSUE TITLE
### Spinner.tsx

### ISSUE THREAD

**Issue by nicolethoen** [RedHatInsights/frontend-components#1872]
file: https://github.com/RedHatInsights/frontend-components/tree/master/packages/components/src/Spinner/Spinner.tsx
 #### Ensure PF4@5 compatibility

**Comment by jenny-s51** [comment]
I'm looking into this one

**Comment by jenny-s51** [comment]
Looks good, v5 spinner is slightly bigger but this is not an issue or a regression

<img width="37" alt="Screenshot 2023-08-10 at 11 02 53 AM" src="https://github.com/RedHatInsights/frontend-components/assets/32821331/7bb54309-7afa-4ea5-a5a6-dfb4ff289375">
<img width="37" alt="Screenshot 2023-08-10 at 11 03 12 AM" src="https://github.com/RedHatInsights/frontend-components/assets/32821331/43deaea3-f699-4b55-8b96-dd0b937c2d02">
