### ISSUE TITLE
### RebootRequired.tsx

### ISSUE THREAD

**Issue by nicolethoen** [RedHatInsights/frontend-components#1873]
file: https://github.com/RedHatInsights/frontend-components/tree/master/packages/advisor-components/src/RebootRequired/RebootRequired.tsx
 #### Ensure PF4@5 compatibility

**Comment by kmcfaul** [comment]
💻

**Comment by kmcfaul** [comment]
No visual change. @nicolethoen or a core dev, do we recommend that our icons be wrapped in the `Icon` class? The svg being used directly in the branch (probably why there's no visual change).

master: 
<img width="184" alt="image" src="https://github.com/RedHatInsights/frontend-components/assets/45077788/5a58ceed-44ff-4c51-bd79-7e9df0a5e0ff">

pf4@5:
<img width="184" alt="image" src="https://github.com/RedHatInsights/frontend-components/assets/45077788/79ad0cb8-c2d9-4cbe-9ed3-16da42bc0ac6">
