### ISSUE TITLE
### Battery.tsx

### ISSUE THREAD

**Issue by nicolethoen** [RedHatInsights/frontend-components#1877]
file: https://github.com/RedHatInsights/frontend-components/tree/master/packages/components/src/Battery/Battery.tsx
 #### Ensure PF4@5 compatibility

**Comment by gitdallas** [comment]
me

**Comment by Hyperkid123** [comment]
@gitdallas If this is the preferred way of creating icons then yes. Use the `Icon` rather than custom CSS.

**Comment by gitdallas** [comment]
Chatted with Coker a bit about this. Sounds like he initially had the same thought, but as this icon is larger he sees why it was done and doesn't think it's worth refactoring especially - especially as it may change the way it interacts in some contexts.

We can close this @nicolethoen
