### ISSUE TITLE
Add const for debounce value

### ISSUE THREAD

**Issue by karelhala** [RedHatInsights/frontend-components#197]
**Is your feature request related to a problem? Please describe.**
There are some magical constants among multiple applications used when debouncing user input. It would be good if we'd were to stick to one number used accross entire platform.

**Describe the solution you'd like**
A const is exported from [@redhat-cloud-services/frontend-components-utilities](https://www.npmjs.com/package/@redhat-cloud-services/frontend-components-utilities)

**Comment by AllenBW** [comment]
oooo watching this, cuz ife can use it when when when 😄
