### ISSUE TITLE
`fec build` hides away error status codes

### ISSUE THREAD

**Issue by ezr-ondrej** [RedHatInsights/frontend-components#2040]
Building is hiding away error codes, which trips CI.

For example: https://github.com/osbuild/image-builder-frontend/actions/runs/10036303735/job/27733799568 (Build stage)
Looks green even tho it errored out.

**Comment by Hyperkid123** [comment]
@ezr-ondrej which version of the package do you use?

**Comment by Hyperkid123** [comment]
We should probably throw a error here: https://github.com/RedHatInsights/frontend-components/blob/master/packages/config/src/bin/build-script.ts#L28

**Comment by ezr-ondrej** [comment]
See a PR with a proposal: https://github.com/RedHatInsights/frontend-components/pull/2041 :)
I think we're on the latest now.
