### ISSUE TITLE
[BUG] Missing spaces between chips in primary toolbar? 

### ISSUE THREAD

**Issue by rvsia** [RedHatInsights/frontend-components#660]
**Describe the bug**

In the latest version, it seems that the primary toolbar's chips groups are missing spacers. Maybe it's a 'feature' in the latest PF, but it looks really weird to me.

![image](https://user-images.githubusercontent.com/32869456/88796334-bc75d480-d1a1-11ea-99ca-18171fe7414b.png)

**Expected behavior**

How it looked before

![image](https://user-images.githubusercontent.com/32869456/88796557-268e7980-d1a2-11ea-9744-41ffd19d0797.png)

Official documentation (maybe obsolete)

![image](https://user-images.githubusercontent.com/32869456/88796389-d2839500-d1a1-11ea-8f29-fd31e120d66d.png)

https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/filters

**Desktop (please complete the following information):**
 - OS: fedora
 - Browser chrome
 - Version 81.0.4044.129

cc @karelhala @Hyperkid123

**Comment by karelhala** [comment]
@rvsia thanks for opening this issue, looks like PF goofed up and removed the padding. We should probably mimic what was there earlier so we don't have to wait for PF.

**Comment by rvsia** [comment]
@karelhala Is there any progress on this? The bot is killing this. :D

**Comment by karelhala** [comment]
@rvsia there's this PR that addresses it https://github.com/RedHatInsights/frontend-components/pull/647 but we got a message from PF not to follow with it. @PanSpagetka any news on this? I'd merge what you have done and deal with PF problems later down the line.

**Comment by PanSpagetka** [comment]
Unfortunately, #647 doesn't fix spacing between chip groups issue.
