### ISSUE TITLE
Display text translations in Components

### ISSUE THREAD

**Issue by zanewoodfin** [RedHatInsights/frontend-components#689]
**Is your feature request related to a problem? Please describe.**
[Subscription Watch](https://github.com/RedHatInsights/curiosity-frontend) uses this library and all of the text ther is translated with i18n/i18next.  We want to be able to use shared components from this library that contain standard text (in particular Maintenance and NotAuthorized).  Unfortunately the text of those components is not translated, so using them would cause us to have a mix of translated and untranslated text.

**Describe the solution you'd like**
I would like for translations of all display text in components of this library to be built into the library somehow.

**Describe alternatives you've considered**
An alternative solution might be to have all text in components overwritable via props, so that we could replace every instance of text with similar text that's translated, but that would create unnecessary redundancy and diversion between apps using this library.

**Comment by karelhala** [comment]
@zanewoodfin thank you for opening this ticket, I've opened JIRA ticket to track this properly on our board. Also is there any reason why you are using `i18next` library? We have built in support for `react-intl` so there might be some problems with generic texts, not that it would effect this issue, just in long term.

**Comment by zanewoodfin** [comment]
@karelhala I saw your response here a while ago, and then completely forgot to get back to you.  I'm sorry about that.  I did not personally know why we use i18next, so I've asked @cdcabrera why we use it and this was his response:

> 1. i18next was used across the prior iterations of this GUI, Cloud Meter, Quipucords
> 2. Cost Management our sister app also uses it
> 3. The ability to use a remote JSON file instead of compiling it in... since this is a browser based utility it kinnnnnda makes more sense

and

> ... also the way it's setup now... we could technically dump in another tool in its place passed through the props... I think some of the string syntax would need to be updated
> ... oh and there was one more aspect, but this applies to all of the translation tools with JSON resources... we got CCS used to JSON file
> now all they have to do is scan it
