### ISSUE TITLE
[BUG] Notifications package 2.2.0 includes path to travis

### ISSUE THREAD

**Issue by rvsia** [RedHatInsights/frontend-components#716]
**Describe the bug**

Sources UI cannot run Notification 2.0.0

```jsx
ERROR in ./node_modules/@redhat-cloud-services/frontend-components-notifications/cjs/NotificationPortal.js
Module not found: Error: Can't resolve 'home/travis/build/RedHatInsights/frontend-components/node_modules/@patternfly/react-core/dist/js/components/Alert/Alert.js' in '/home/rvsianskz/insightsproject/sources-ui/node_modules/@redhat-cloud-services/frontend-components-notifications/cjs'
 @ ./node_modules/@redhat-cloud-services/frontend-components-notifications/cjs/NotificationPortal.js 1:517-650
```

bundled package:

`@redhat-cloud-services/frontend-components-notifications/cjs/NotificationPortal.js`

`
Alert_js=require("home/travis/build/RedHatInsights/frontend-components/node_modules/@patternfly/react-core/dist/js/components/Alert/Alert.js"),TextContent_js=require("home/travis/build/RedHatInsights/frontend-components/node_modules/@patternfly/react-core/dist/js/components/Text/TextContent.js"),Text_js=require("home/travis/build/RedHatInsights/frontend-components/node_modules/@patternfly/react-core/dist/js/components/Text/Text.js"),AlertActionCloseButton_js=require("home/travis/build/RedHatInsights/frontend-components/node_modules/@patternfly/react-core/dist/js/components/Alert/AlertActionCloseButton.js"),CloseIcon=_interopDefault(require("@patternfly/react-icons/dist/js/icons/close-icon")),Card_js=require("home/travis/build/RedHatInsights/frontend-components/node_modules/@patternfly/react-core/dist/js/components/Card/Card.js"),CardBody_js=require("home/travis/build/RedHatInsights/frontend-components/node_modules/@patternfly/react-core/dist/js/components/Card/CardBody.js"),Button_js=require("home/travis/build/RedHatInsights/frontend-components/node_modules/@patternfly/react-core/dist/js/components/Button/Button.js"),Pagination_js=require("home/travis/build/RedHatInsights/frontend-components/node_modules/@patternfly/react-core/dist/js/components/Pagination/Pagination.js"),Level_js=require("home/travis/build/RedHatInsights/frontend-components/node_modules/@patternfly/react-core/dist/js/layouts/Level/Level.js"),LevelItem_js=require("home/travis/build/RedHatInsights/frontend-components/node_modules/@patternfly/react-core/dist/js/layouts/Level/LevelItem.js"),
`

@karelhala

**Comment by karelhala** [comment]
Yeah we've changed the build and introduced this bug in https://github.com/RedHatInsights/frontend-components/pull/700 we've fixed that in https://github.com/RedHatInsights/frontend-components/pull/711 but that'll reguire manual releases as the auto releaser was not triggered because of not hitting all affected packages.
