### ISSUE TITLE
[BUG] NotAuthorized component links to /beta/beta/settings/my-user-access in beta

### ISSUE THREAD

**Issue by josejulio** [RedHatInsights/frontend-components#892]
**Describe the bug**

When the NotAuthorized component shows in a beta environment, it has an invalid link: `/beta/beta/settings/my-user-access`

**To Reproduce**
1. Go to a page that shows the `NotAuthorized` component in a beta environment.
2. See where the `My User Access` link points to.
3. Click it.
4. See 404 error. 

**Expected behavior**
Link should be: `/beta/settings/my-user-access`

**Desktop (please complete the following information):**
 - OS: Fedora 33
 - Browse:r Chrome 
 - Version: 87.0.4280.66 (Official Build) (64-bit)

**Additional context**
I think the issue is because all the beta pages have the `<base href=/beta/>` and the [component also adds](https://github.com/RedHatInsights/frontend-components/blob/master/packages/components/src/Components/NotAuthorized/NotAuthorized.js#L19) the `./beta`

**Comment by josejulio** [comment]
@karelhala @ryelo  Wondering if is OK from your POV to remove that `beta/` from https://github.com/RedHatInsights/frontend-components/blob/master/packages/components/src/Components/NotAuthorized/NotAuthorized.js#L19

**Comment by karelhala** [comment]
@josejulio yeah, that's definetly a bug, when we used both `./` and calculated the beta ourselves.
