### ISSUE TITLE
[BUG] Module federation breaks in typescript when trying to import `react`

### ISSUE THREAD

**Issue by josejulio** [RedHatInsights/frontend-components#947]
**Describe the bug**

I get the following error when loading the page, nothing else loads:

```
Uncaught (in promise) Error: Shared module is not available for eager consumption: webpack/sharing/consume/default/react/react
    at Object.__webpack_modules__.<computed> (consumes:137)
    at __webpack_require__ (bootstrap:21)
    at fn (hot module replacement:61)
    at Module../src/bootstrap-dev.js (App.js:43)
    at __webpack_require__ (bootstrap:21)
    at fn (hot module replacement:61)
    at entry-dev.tsx:21
```

**To Reproduce**

I created a reproducer from the [frontend-starter-app](https://github.com/RedHatInsights/frontend-starter-app)

1. Clone frontend-app-starter
2. Install typescript
3. Rename `entry-dev.js` to `entry-dev.tsx` and add a tsconfig file
4. Start and open in browser
5. See error in console

Or instead of steps 1-4 use this commit: https://github.com/RedHatInsights/frontend-starter-app/commit/92ea132d1113ef18713e217ec919a5c348e4197f

**Expected behavior**
It should work show the starter application

**Desktop (please complete the following information):**
 - OS: Fedora
 - Browser Chrome
 - Version Version 87.0.4280.66 (Official Build) (64-bit)

**Additional context**
There should be some step for the ts/tsx files that is missing in the config. Any hint on what to look would be appreciated.

**Comment by josejulio** [comment]
Looks like having the `entry` files as `js` does the trick.

`entry-dev.js`
```js
import('./bootstrap-dev');
```

`bootstrap-dev` is a typescript file.

I'll keep testing and will close this issue if everything seems fine.

**Comment by rajsenthil** [comment]
I got struck for many days until I saw this message. Thanks.

**Comment by josejulio** [comment]
Glad that it was useful. I ran into other issues (resolved by now), so let me know and I might be able to help.

**Comment by chrispcode** [comment]
Hey guys, I was able to solve this by using this typescript configuration:

```json
{
  "include": ["src/**/*"],
  "compilerOptions": {                   
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "jsx": "react",
    "strict": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "forceConsistentCasingInFileNames": true,
  }
}
```

`module` to `esnext` and `moduleResolution` to `node` is what I think did the trick!

**Comment by chrispcode** [comment]
and yes, my bootstrap file is called: `bootstrap.tsx`
and here is my request sequence: 

<img width="1401" alt="image" src="https://user-images.githubusercontent.com/7029482/112492754-d348e700-8d81-11eb-9b61-b2559ca8e6d5.png">
